### ISSUE TITLE
Don't publish your keystore

### ISSUE THREAD

**Issue by Schamper** [ReyKoxha/nodebb-webview#1]
You should probably generate a new one for good measure.

**Comment by ReyKoxha** [comment]
Already replaced with an empty one ;)

**Comment by Schamper** [comment]
Can still view it in [git history](https://github.com/ReyKoxha/nodebb-webview/blob/4ea371a790e80f0a03a8b6d715b8e26c8b22709b/extras/keystore/webviewapp.keystore) tho.
