### ISSUE TITLE
Missing something!

### ISSUE THREAD

**Issue by lovebdsobuj** [ReyKoxha/nodebb-webview#2]
Hello sir,

Good day.

Is there missing a feature 
# Refresh/Pull to Refresh

**Comment by ReyKoxha** [comment]
Hey,

this feature had been removed as NodeBB is always "live".

**Comment by lovebdsobuj** [comment]
Hi 
It's good to know that NodeBB is as always "LIVE".

But, 

If network connection trouble then, must need to refresh. 

Can I get pull to refresh code for this app?

**Comment by ReyKoxha** [comment]
It would require some extra work and as it is rather disturbing I won't add it anytime soon.

However, you could try and follow the Google docs for a swipe container.

**Comment by lovebdsobuj** [comment]
Okay, sir. Thank you. I'll try.
