### ISSUE TITLE
Releases

### ISSUE THREAD

**Issue by msfjarvis** [ReyKoxha/nodebb-webview#3]
I run a NodeBB forum at [https://technologistguild.com](https://technologistguild.com) and would love to be able to offer this application as a method to access the forums. Can you please comment which part of the code would need changes and if not inconvenient, compile it for us?

**Comment by ReyKoxha** [comment]
You need to modify the navigation.xml. The code is commented, so it shouldn't be an issue.

Unfortunately, I won't compile the code, unless you pay for it. ;)
