### ISSUE TITLE
(Google Play Services Library Error)

### ISSUE THREAD

**Issue by mgilank** [ReyKoxha/nodebb-webview#7]
no notification receive, in onesignal i got this error
**Google Play Services Library Error**

https://i.imgur.com/W41sG8p.png

**Comment by ReyKoxha** [comment]
I am hooking into this right now and will try to compile the app from the source code on GitHub.

**Comment by ReyKoxha** [comment]
Fixed with the latest commit.
Be sure to set a GCM Sender ID in the strings.xml.
