### ISSUE TITLE
Failure to Rebuild Project

### ISSUE THREAD

**Issue by lilbud** [ReyKoxha/nodebb-webview#8]
I am going though your tutorial on building the app and have run into some issues. Every single time I attempt to rebuild the project, I will get numerous errors. The error is `error: package R does not exist`, I get this every time I try to rebuild and can't proceed further.

**Comment by ReyKoxha** [comment]
Try to clean your project.

**Comment by lilbud** [comment]
I have tried cleaning it several times, the only thing that comes up is the warning 
`warning: string 'admob_test_device_id' has no default translation.`
`warning: string 'admob_unit_id' has no default translation.`

**Comment by ReyKoxha** [comment]
That shouldn't be the issue. You should check the imports. There should be one with the R. Replace the package with yours. So, e.g.:
mylittle.sample.app.R to mynew.real.app.R

Then clean and rebuild the project again.
